// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc-V3SCKh5GydipcGyNKT4kLZX0whcatA',
    appId: '1:1059284167916:web:4a50ebb5066592492e89c9',
    messagingSenderId: '1059284167916',
    projectId: 'practice2-29042001',
    authDomain: 'practice2-29042001.firebaseapp.com',
    storageBucket: 'practice2-29042001.firebasestorage.app',
    measurementId: 'G-D0SEJWQ3CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkX_2CbHYR723adLrMMLaI_J5DdLoSwQc',
    appId: '1:1059284167916:android:f396504a17a294482e89c9',
    messagingSenderId: '1059284167916',
    projectId: 'practice2-29042001',
    storageBucket: 'practice2-29042001.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc-V3SCKh5GydipcGyNKT4kLZX0whcatA',
    appId: '1:1059284167916:web:c2d0cf5d7cf5521c2e89c9',
    messagingSenderId: '1059284167916',
    projectId: 'practice2-29042001',
    authDomain: 'practice2-29042001.firebaseapp.com',
    storageBucket: 'practice2-29042001.firebasestorage.app',
    measurementId: 'G-R32GRHMQ12',
  );

}